### PR TITLE
Fix CMakeLists.txt to use local directory

### PR DESCRIPTION
**Pull request by Prior99**

### CODE REVIEW

**Comment by Svalorzen** [comment]
Would you mind explaining why this change is necessary and what problem it fixes?

**Comment by Prior99** [comment]
Sure. Thanks for taking a look at this PR.

It tells CMake to look at the `cmake/` directory inside your repository instead of the one CMake is invoked in.

I am using your repository as a submodule in my repository and when I run my CMake I am getting the following error:

```
mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && make -j
CMake Error at 3rdparty/cpp-readline/CMakeLists.txt:30 (find_package):
  By not providing "FindReadline.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Readline",
  but CMake did not find one.

  Could not find a package configuration file provided by "Readline" with any
  of the following names:

    ReadlineConfig.cmake
    readline-config.cmake

  Add the installation prefix of "Readline" to CMAKE_PREFIX_PATH or set
  "Readline_DIR" to a directory containing one of the above files.  If
  "Readline" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/prior/repositories/ppg/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:3: default] Error 1
```

Because CMake looks for the `cmake/modules/FindReadline.cmake` in my project.

This is fixed when using `CMAKE_CURRENT_SOURCE_DIR` instead of `CMAKE_SOURCE_DIR` which will find that file in this directory instead.

**Comment by Svalorzen** [comment]
Ah, I see. Makes sense. I didn't know this, and so I started looking around, and I realized that another variable which could maybe do this is `CMAKE_PROJECT_DIR`.

Do you know if it would be better to use that one? I'm not sure there's a difference, maybe you know.

**Comment by Prior99** [comment]
Hm. I am not sure, I think `CMAKE_PROJECT_DIR` would also point the directory in which CMake is invoked.

**Comment by Svalorzen** [comment]
Alright, I did a bunch of experiments and it looks like:

- `CMAKE_SOURCE_DIR` refers to the uppermost directory of all `CMakeLists.txt` found
- `CMAKE_CURRENT_SOURCE_DIR` refers to the directory of the current `CMakeLists.txt` being parsed
- `PROJECT_SOURCE_DIR` refers to the directory of the last `CMakeLists.txt` that did the `project()` command.

So in our case they are the same since the command to include the modules is in the uppermost `CMakeLists.txt` of the project. Still I'd prefer the `PROJECT_SOURCE_DIR` just because it's more "correct" from an ideal point of view.

If you can change your PR to use that variable I'll merge it. Thanks again for bringing this up!

**Comment by Prior99** [comment]
But in the official docs it says:

**CMAKE_CURRENT_SOURCE_DIR**
this is the directory where the currently processed CMakeLists.txt is located in

**PROJECT_SOURCE_DIR**
contains the full path to the root of your project source directory, i.e. to the nearest directory where CMakeLists.txt contains the PROJECT() command

For me the first one sounds more correct. I am not sure if the 2nd one has any other implications.

I tested it with both and both worked. Hm.

**Comment by Svalorzen** [comment]
Well, the modules folder in our case is located on the root dir of the project, so saying that the path begins with `PROJECT_SOURCE_DIR` makes sense to me. The fact that we're referencing it from a CMakeLists.txt that happens to be on the root too is a "coincidence".

If you had to reference that folder from someplace else for some reason you wouldn't be able to use the `CMAKE_CURRENT_SOURCE_DIR` then, which is why I prefer the other one.

We're also sure that the `PROJECT_SOURCE_DIR` is going to be the right folder because that's where we define the project. Subprojects will have their own `project()` calls which will modify it for them.

**Comment by Prior99** [comment]
Okay. Here you go.

**Comment by Svalorzen** [comment]
Thanks!

**Pull request merged**
